services:
  - type: web
    name: drona-ai-chatbot
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn chtbt_api:app --host 0.0.0.0 --port $PORT --workers 1"
    plan: free
    autoDeploy: true
    region: singapore
    envVars:
      GEMINI_API_KEY: 
        sync: false
      CHROMA_API_KEY:
        sync: false
      CHROMA_TENANT:
        sync: false
      CHROMA_DATABASE: "RAG_Chatbot_1_nerv"
      CHROMA_COLLECTION: "alumni_collection"
