services:
  - type: web
    name: drona-ai-chatbot
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn chtbt_api:app --host 0.0.0.0 --port $PORT"
    plan: free
    autoDeploy: true
    region: singapore
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: CHROMA_API_KEY
        sync: false
      - key: CHROMA_HOST
        value: "https://api.trychroma.com"
