services:
  - type: web
    name: drona-ai-chatbot
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn chtbt_api:app --host 0.0.0.0 --port $PORT --workers 1"
    plan: free
    autoDeploy: true
    region: singapore
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: CHROMA_API_KEY
        sync: false
      - key: CHROMA_TENANT
        sync: false       
      - key: CHROMA_DATABASE
        value: "RAG_Chatbot_1_nerv"  
      - key: CHROMA_COLLECTION
        value: "alumni_collection"
